version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        volumes:
            - ./zookeeper_data:/opt/zookeeper-3.4.6/data
        container_name: zookeeper
        ports:
            - "10002:2181"
            - "10003:2182"
        restart: always
    kafka:
        image: wurstmeister/kafka
        container_name: kafka_01
        depends_on:
            - zookeeper
        ports:
            - "10004:9092"
        volumes:
            - ./kafka_log:/kafka
        environment:
            - KAFKA_BROKER_NO=0
            - KAFKA_BROKER_ID=0
            - KAFKA_LISTENERS=PLAINTEXT://kafka_01:9092                     # kafka tcp 侦听的ip
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://服务器ip:10004        # kafka broker侦听的ip
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_HEAP_OPTS=-Xmx512M -Xms16M
        restart: always
    # kafka集群管理面板
    kafka_manager:
        image: sheepkiller/kafka-manager
        ports:
            - "10005:9000"
        environment:
            - ZK_HOSTS=zookeeper:2181
        depends_on:
            - zookeeper
            - kafka
        restart: always